/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pages;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import project.ConnectionProvider;

/**
 *
 * @author fekede alemayehu
 */
public class admin_page extends javax.swing.JFrame {

    /**
     * Creates new form teacher_page
     */
    public admin_page() {
        initComponents();
                   try {
            String course_nam=course_name1.getText();
            String course_cd=course_code1.getText();
            
            Connection con = ConnectionProvider.getCon();
            Statement st=con.createStatement();

         ResultSet res = st.executeQuery("select name from login_credentials where role_type='teacher' ");
         
          while(res.next()){
            String se=res.getString("name");
           teacher_list.addItem(se);          
           }
          Connection cone = ConnectionProvider.getCon();
            Statement ls=cone.createStatement();
          ResultSet rs = ls.executeQuery("select course_name from course ");
          while(rs.next()){
            String s=rs.getString("course_name");
           course_list.addItem(s);
           course_list2.addItem(s);          
           }
  
            // TODO add your handling code here:
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_5 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane8 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        id = new javax.swing.JLabel();
        Stud_name1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        Stud_name3 = new javax.swing.JLabel();
        stud_name1 = new javax.swing.JTextField();
        std_id = new javax.swing.JTextField();
        std_password = new javax.swing.JTextField();
        std_section = new javax.swing.JComboBox<>();
        Std_addbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        name6 = new javax.swing.JLabel();
        delete_student = new javax.swing.JTextField();
        teach_addbtn4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        id6 = new javax.swing.JLabel();
        stud_id = new javax.swing.JTextField();
        teach_addbtn5 = new javax.swing.JButton();
        stud_name = new javax.swing.JTextField();
        name7 = new javax.swing.JLabel();
        id7 = new javax.swing.JLabel();
        stud_ID = new javax.swing.JTextField();
        Stud_name11 = new javax.swing.JLabel();
        Stud_pass = new javax.swing.JTextField();
        Stud_name12 = new javax.swing.JLabel();
        sec_teach2 = new javax.swing.JComboBox<>();
        teach_addbtn6 = new javax.swing.JButton();
        jTabbedPane10 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        sec_number = new javax.swing.JTextField();
        add_sectionbtn = new javax.swing.JButton();
        jTabbedPane11 = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        teacher_list = new javax.swing.JComboBox<>();
        course_list = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        Assign_btn = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        course_name1 = new javax.swing.JTextField();
        add_coursebtn2 = new javax.swing.JButton();
        course_code1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        delete_coursebtn = new javax.swing.JButton();
        course_list2 = new javax.swing.JComboBox<>();
        jTabbedPane9 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        name1 = new javax.swing.JLabel();
        teach_name = new javax.swing.JTextField();
        id1 = new javax.swing.JLabel();
        teach_id = new javax.swing.JTextField();
        Stud_name4 = new javax.swing.JLabel();
        teacher_pass = new javax.swing.JTextField();
        sec_teach = new javax.swing.JComboBox<>();
        Stud_name2 = new javax.swing.JLabel();
        teach_addbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        delete_teacher_name = new javax.swing.JTextField();
        name4 = new javax.swing.JLabel();
        teach_addbtn1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        name5 = new javax.swing.JLabel();
        teach_name1 = new javax.swing.JTextField();
        teach_id1 = new javax.swing.JTextField();
        id4 = new javax.swing.JLabel();
        Stud_name9 = new javax.swing.JLabel();
        teacher_pass1 = new javax.swing.JTextField();
        sec_teach1 = new javax.swing.JComboBox<>();
        Stud_name10 = new javax.swing.JLabel();
        teach_addbtn2 = new javax.swing.JButton();
        id5 = new javax.swing.JLabel();
        teach_id2 = new javax.swing.JTextField();
        teach_addbtn3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admni illustration-2.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(340, 130));
        setLocationByPlatform(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(0, 0, 0));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        sidepanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 30, -1, -1));
        sidepanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 300, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admni illustration-2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        sidepanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 150));

        btn_5.setBackground(new java.awt.Color(0, 0, 0));
        btn_5.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btn_5.setForeground(new java.awt.Color(255, 255, 255));
        btn_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_student_male_26px.png"))); // NOI18N
        btn_5.setText("          Manage Students               ");
        btn_5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_5.setBorderPainted(false);
        btn_5.setContentAreaFilled(false);
        btn_5.setFocusPainted(false);
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });
        sidepanel.add(btn_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 250, 50));

        btn_2.setBackground(new java.awt.Color(0, 0, 0));
        btn_2.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btn_2.setForeground(new java.awt.Color(255, 255, 255));
        btn_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_school_filled_26px_1.png"))); // NOI18N
        btn_2.setText("         Manage  Sections         ");
        btn_2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_2.setBorderPainted(false);
        btn_2.setContentAreaFilled(false);
        btn_2.setFocusPainted(false);
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });
        sidepanel.add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 250, 50));

        btn_3.setBackground(new java.awt.Color(0, 0, 0));
        btn_3.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btn_3.setForeground(new java.awt.Color(255, 255, 255));
        btn_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_courses_23px.png"))); // NOI18N
        btn_3.setText("          Manage Courses            ");
        btn_3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_3.setBorderPainted(false);
        btn_3.setContentAreaFilled(false);
        btn_3.setFocusPainted(false);
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });
        sidepanel.add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 250, 50));

        btn_4.setBackground(new java.awt.Color(0, 0, 0));
        btn_4.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btn_4.setForeground(new java.awt.Color(255, 255, 255));
        btn_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_school_director_23px_4.png"))); // NOI18N
        btn_4.setText("          Manage Teacher                ");
        btn_4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_4.setBorderPainted(false);
        btn_4.setContentAreaFilled(false);
        btn_4.setFocusPainted(false);
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });
        sidepanel.add(btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 250, 50));

        jLabel10.setForeground(new java.awt.Color(51, 204, 0));
        jLabel10.setText("@abudah 2021");
        sidepanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 100, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 255, 0));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_admin_settings_male_30px.png"))); // NOI18N
        jLabel14.setText("System Admin");
        sidepanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 140, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_settings_3_30px_2.png"))); // NOI18N
        jButton1.setText("           Log Out        ");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        sidepanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 250, 30));

        bg.add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 480));

        jPanel6.setBackground(new java.awt.Color(153, 51, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(51, 102, 0));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/handsup.jpg"))); // NOI18N
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 740, 90));

        jTabbedPane8.setBackground(new java.awt.Color(255, 255, 102));
        jTabbedPane8.setForeground(new java.awt.Color(255, 51, 0));
        jTabbedPane8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        id.setText("ID number: ");
        jPanel9.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 110, 30));

        Stud_name1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        Stud_name1.setText("Section: ");
        jPanel9.add(Stud_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 90, 30));

        name.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        name.setText("Name:");
        jPanel9.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 60, 30));

        Stud_name3.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        Stud_name3.setText("Password: ");
        jPanel9.add(Stud_name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 90, 30));

        stud_name1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jPanel9.add(stud_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 150, -1));

        std_id.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jPanel9.add(std_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 150, -1));

        std_password.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jPanel9.add(std_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 150, -1));

        std_section.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        std_section.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std_sectionActionPerformed(evt);
            }
        });
        jPanel9.add(std_section, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 150, -1));

        Std_addbtn.setBackground(new java.awt.Color(255, 0, 102));
        Std_addbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        Std_addbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_add_30px.png"))); // NOI18N
        Std_addbtn.setText("Add");
        Std_addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Std_addbtnActionPerformed(evt);
            }
        });
        jPanel9.add(Std_addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, -1, 36));

        jLabel2.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jLabel2.setText("Enter the Details below to add Student:  ");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 490, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setMaximumSize(new java.awt.Dimension(1038, 100));
        jLabel4.setMinimumSize(new java.awt.Dimension(1038, 100));
        jLabel4.setPreferredSize(new java.awt.Dimension(1038, 500));
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 360));

        jTabbedPane8.addTab("Register Student", jPanel9);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel7.setText("Enter the ID number of the Student to Delete:");
        jPanel15.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 450, 30));

        name6.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        name6.setText("ID number:");
        jPanel15.add(name6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 80, 30));

        delete_student.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jPanel15.add(delete_student, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 150, -1));

        teach_addbtn4.setBackground(new java.awt.Color(255, 0, 0));
        teach_addbtn4.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        teach_addbtn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_delete_30px_1.png"))); // NOI18N
        teach_addbtn4.setText("Delete");
        teach_addbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teach_addbtn4ActionPerformed(evt);
            }
        });
        jPanel15.add(teach_addbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, -1, 36));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Couple.jpg"))); // NOI18N
        jPanel15.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 360));

        jTabbedPane8.addTab("Delete Student", jPanel15);

        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id6.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        id6.setText("ID number: ");
        jPanel16.add(id6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 110, 30));

        stud_id.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jPanel16.add(stud_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 150, -1));

        teach_addbtn5.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        teach_addbtn5.setText("Search");
        teach_addbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teach_addbtn5ActionPerformed(evt);
            }
        });
        jPanel16.add(teach_addbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, 36));

        stud_name.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jPanel16.add(stud_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 150, -1));

        name7.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        name7.setText("Name:");
        jPanel16.add(name7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 60, 30));

        id7.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        id7.setText("ID number: ");
        jPanel16.add(id7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 110, 30));

        stud_ID.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jPanel16.add(stud_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 150, -1));

        Stud_name11.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        Stud_name11.setText("Password: ");
        jPanel16.add(Stud_name11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 90, 30));

        Stud_pass.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jPanel16.add(Stud_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 150, -1));

        Stud_name12.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        Stud_name12.setText("Section: ");
        jPanel16.add(Stud_name12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 90, 30));

        sec_teach2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jPanel16.add(sec_teach2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 150, -1));

        teach_addbtn6.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        teach_addbtn6.setText("Update");
        teach_addbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teach_addbtn6ActionPerformed(evt);
            }
        });
        jPanel16.add(teach_addbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, -1, 36));

        jTabbedPane8.addTab("Update Student Details", jPanel16);

        jTabbedPane2.addTab("Manage Student", jTabbedPane8);

        jTabbedPane10.setForeground(new java.awt.Color(255, 0, 0));
        jTabbedPane10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel8.setText("Section number: ");
        jPanel11.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel11.setText("Create new Section: ");
        jPanel11.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        sec_number.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jPanel11.add(sec_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 130, 20));

        add_sectionbtn.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        add_sectionbtn.setText("Add");
        add_sectionbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_sectionbtnActionPerformed(evt);
            }
        });
        jPanel11.add(add_sectionbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, 40));

        jTabbedPane10.addTab("Create new Section", jPanel11);

        jTabbedPane2.addTab("Manage Section", jTabbedPane10);

        jTabbedPane11.setForeground(new java.awt.Color(255, 0, 0));
        jTabbedPane11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel9.setText("Teacher:");
        jPanel12.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 124, 39));

        teacher_list.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        teacher_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacher_listActionPerformed(evt);
            }
        });
        jPanel12.add(teacher_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 200, 30));

        course_list.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        course_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course_listActionPerformed(evt);
            }
        });
        jPanel12.add(course_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 200, 30));

        jLabel12.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel12.setText("Course:  ");
        jPanel12.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 124, 39));

        Assign_btn.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        Assign_btn.setText("Assign");
        Assign_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Assign_btnActionPerformed(evt);
            }
        });
        jPanel12.add(Assign_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, 40));

        jTabbedPane11.addTab("Assign Course", jPanel12);

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel19.setText("Add New Course:");
        jPanel14.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 180, -1));

        jLabel20.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel20.setText("Course Name:  ");
        jPanel14.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        course_name1.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jPanel14.add(course_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 170, 30));

        add_coursebtn2.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        add_coursebtn2.setText("Add");
        add_coursebtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_coursebtn2ActionPerformed(evt);
            }
        });
        jPanel14.add(add_coursebtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, 40));

        course_code1.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jPanel14.add(course_code1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 170, 30));

        jLabel21.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel21.setText("Course Code:  ");
        jPanel14.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jTabbedPane11.addTab("Add new Course", jPanel14);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel22.setText("Course Name:  ");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jLabel23.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel23.setText("Delete Course:");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 180, -1));

        delete_coursebtn.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        delete_coursebtn.setText("Delete");
        delete_coursebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_coursebtnActionPerformed(evt);
            }
        });
        jPanel4.add(delete_coursebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, 40));

        course_list2.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        course_list2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course_list2ActionPerformed(evt);
            }
        });
        jPanel4.add(course_list2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 200, 30));

        jTabbedPane11.addTab("Delete Course", jPanel4);

        jTabbedPane2.addTab("Manage Course", jTabbedPane11);

        jTabbedPane9.setForeground(new java.awt.Color(255, 0, 0));
        jTabbedPane9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        name1.setText("Name:");
        jPanel10.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 60, 30));

        teach_name.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jPanel10.add(teach_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 150, -1));

        id1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        id1.setText("ID number: ");
        jPanel10.add(id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 110, 30));

        teach_id.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jPanel10.add(teach_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 150, -1));

        Stud_name4.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        Stud_name4.setText("Password: ");
        jPanel10.add(Stud_name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 90, 30));

        teacher_pass.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jPanel10.add(teacher_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 150, -1));

        sec_teach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jPanel10.add(sec_teach, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 150, -1));

        Stud_name2.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        Stud_name2.setText("Section: ");
        jPanel10.add(Stud_name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 90, 30));

        teach_addbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        teach_addbtn.setText("Add");
        teach_addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teach_addbtnActionPerformed(evt);
            }
        });
        jPanel10.add(teach_addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, -1, 36));

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel3.setText("Enter the Details below add Teacher:  ");
        jPanel10.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 300, 30));

        jTabbedPane9.addTab("Register New Teacher", jPanel10);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel6.setText("Enter the ID number of the Teacher:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 300, 30));

        delete_teacher_name.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jPanel1.add(delete_teacher_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 150, -1));

        name4.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        name4.setText("ID number:");
        jPanel1.add(name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 80, 30));

        teach_addbtn1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        teach_addbtn1.setText("Delete");
        teach_addbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teach_addbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(teach_addbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, 36));

        jTabbedPane9.addTab("Delete Registered Teacher", jPanel1);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name5.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        name5.setText("Name:");
        jPanel3.add(name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 60, 30));

        teach_name1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jPanel3.add(teach_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 150, -1));

        teach_id1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jPanel3.add(teach_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 150, -1));

        id4.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        id4.setText("ID number: ");
        jPanel3.add(id4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 110, 30));

        Stud_name9.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        Stud_name9.setText("Password: ");
        jPanel3.add(Stud_name9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 90, 30));

        teacher_pass1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jPanel3.add(teacher_pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 150, -1));

        sec_teach1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jPanel3.add(sec_teach1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 150, -1));

        Stud_name10.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        Stud_name10.setText("Section: ");
        jPanel3.add(Stud_name10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 90, 30));

        teach_addbtn2.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        teach_addbtn2.setText("Search");
        teach_addbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teach_addbtn2ActionPerformed(evt);
            }
        });
        jPanel3.add(teach_addbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, 36));

        id5.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        id5.setText("ID number: ");
        jPanel3.add(id5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 110, 30));

        teach_id2.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jPanel3.add(teach_id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 150, -1));

        teach_addbtn3.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        teach_addbtn3.setText("Update");
        teach_addbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teach_addbtn3ActionPerformed(evt);
            }
        });
        jPanel3.add(teach_addbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, -1, 36));

        jTabbedPane9.addTab("Update the details", jPanel3);

        jTabbedPane2.addTab("Manage Teacher", jTabbedPane9);

        jPanel6.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 740, 410));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jTabbedPane5.addTab("tab1", jPanel6);

        jTabbedPane1.addTab("tab 3", jTabbedPane5);

        bg.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, -70, 750, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 990, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        // TODO add your handling code here:

           setColor(btn_5);
           resetColor(btn_2,btn_3,btn_4);
           jTabbedPane2.setSelectedIndex(0);           
      
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        // TODO add your handling code here:

           setColor(btn_2);
           resetColor(btn_3,btn_4,btn_5);
           jTabbedPane2.setSelectedIndex(1);           
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        // TODO add your handling code here:

           setColor(btn_3);
           resetColor(btn_2,btn_4,btn_5);
           jTabbedPane2.setSelectedIndex(2);           
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        // TODO add your handling code here:

           setColor(btn_4);
           resetColor(btn_2,btn_3,btn_5);
           jTabbedPane2.setSelectedIndex(3);           
    }//GEN-LAST:event_btn_4ActionPerformed

    private void course_list2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course_list2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course_list2ActionPerformed

    private void delete_coursebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_coursebtnActionPerformed

         String course_name=(String)course_list2.getSelectedItem();
            try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            st.executeUpdate("delete FROM course WHERE course_name ='"+course_name+"'");
            JOptionPane.showMessageDialog(null, "successfuly deleted ");
            course_list.removeItem(course_name);
            course_list2.removeItem(course_name);
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_delete_coursebtnActionPerformed

    private void add_coursebtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_coursebtn2ActionPerformed
        try {
            String course_name=course_name1.getText();
             String  course_num=course_code1.getText();

            Connection con = ConnectionProvider.getCon();
            Statement st=con.createStatement();

            st.executeUpdate("INSERT INTO course VALUES ('"+course_name+"','"+course_num+"');");
            course_list.addItem(course_name);
            course_list2.addItem(course_name);
            course_name1.setText(" ");
            course_code1.setText(" ");
            JOptionPane.showMessageDialog(null, "Course Added successfully!");

            // TODO add your handling code here:
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }        
        
// TODO add your handling code here:
    }//GEN-LAST:event_add_coursebtn2ActionPerformed

    private void Assign_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Assign_btnActionPerformed
        try {
            String teacher_name=(String)teacher_list.getSelectedItem();
             String  course_name=(String)course_list.getSelectedItem();

            Connection con = ConnectionProvider.getCon();
            Statement st=con.createStatement();

            st.executeUpdate("INSERT INTO assigned_courses VALUES ('"+course_name+"','"+teacher_name+"');");
            JOptionPane.showMessageDialog(null, "Course Assigned successfully!");

            // TODO add your handling code here:
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Assign_btnActionPerformed

    private void course_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course_listActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course_listActionPerformed

    private void teacher_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacher_listActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacher_listActionPerformed

    private void add_sectionbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_sectionbtnActionPerformed
        std_section.addItem(sec_number.getText());
        sec_teach.addItem(sec_number.getText());
        JOptionPane.showMessageDialog(null, "New Section successfully Added to the System!");

        // TODO add your handling code here:
    }//GEN-LAST:event_add_sectionbtnActionPerformed

    private void teach_addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teach_addbtnActionPerformed
        try {
            String teacher_name=teach_name.getText();
            String teacher_id=teach_id.getText();
            String teacher_password=teacher_pass.getText();
            String section_teacher=(String)sec_teach.getSelectedItem();

            Connection con = ConnectionProvider.getCon();
            Statement st=con.createStatement();
            teacher_list.addItem(teach_name.getText());
            st.executeUpdate("INSERT INTO login_credentials VALUES ('"+teacher_name+"','"+teacher_id+"', '"+teacher_password+"', '"+section_teacher+"', 'teacher');");
            JOptionPane.showMessageDialog(null, "Teacher successfully Added to the System!");

            // TODO add your handling code here:
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_teach_addbtnActionPerformed

    private void Std_addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Std_addbtnActionPerformed
        try {
            String stud_name=stud_name1.getText();
            String Std_id=std_id.getText();
            String password=std_password.getText();
            String section=(String)std_section.getSelectedItem();

            Connection con = ConnectionProvider.getCon();
            Statement st=con.createStatement();

            st.executeUpdate("INSERT INTO login_credentials VALUES ('"+stud_name+"','"+Std_id+"', '"+password+"', '"+section+"', 'student');");
            stud_name1.setText(" ");
            std_id.setText("");
            std_password.setText(" ");
            JOptionPane.showMessageDialog(null, "successfully Added to the System!");

            // TODO add your handling code here:
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_Std_addbtnActionPerformed

    private void std_sectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std_sectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std_sectionActionPerformed

    private void teach_addbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teach_addbtn1ActionPerformed
         String teacher_name=delete_teacher_name.getText();
            try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            teacher_list.removeItem(teacher_name);
            
             Connection cone = ConnectionProvider.getCon();
            Statement ste=cone.createStatement();

         ResultSet res = ste.executeQuery("select name from login_credentials WHERE id_number='"+teacher_name+"'");
         
          if (res.next()){
            String se=res.getString(1);
            teacher_list.removeItem(se);          
           }
            
            st.executeUpdate("delete FROM login_credentials WHERE id_number='"+teacher_name+"'");
               delete_teacher_name.setText(" ");
            JOptionPane.showMessageDialog(null, "successfuly deleted ");
            
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_teach_addbtn1ActionPerformed

    private void teach_addbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teach_addbtn2ActionPerformed
            String teach_id= teach_id2.getText();
 
 try{
     Connection con =ConnectionProvider.getCon();   
       Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("select *from login_credentials where id_number ='"+teach_id+"'");
        if (rs.next()){
        teach_name1.setText(rs.getString(1));
        teach_id1.setText(rs.getString(2));
        teacher_pass1.setText(rs.getString(3));
        }

 }catch(Exception e){
  
    JOptionPane.showMessageDialog(null, e);
}        // TODO add your handling code here:
    }//GEN-LAST:event_teach_addbtn2ActionPerformed

    private void teach_addbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teach_addbtn3ActionPerformed
         String teacher_name= teach_name1.getText();
         String teacher_id=teach_id1.getText();
         String teacher_password=teacher_pass1.getText();
    try{
        Connection con =ConnectionProvider.getCon();
        Statement st = con.createStatement();
           st.executeUpdate("update login_credentials set name='"+teacher_name+"',id_number='"+teacher_id+"',password='"+teacher_password+"' where id_number='"+teacher_id+"'");
        JOptionPane.showMessageDialog(null, "Teacher Info successfully updated");
          }catch (Exception e){
             JOptionPane.showMessageDialog(null, "connection error");
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_teach_addbtn3ActionPerformed

    private void teach_addbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teach_addbtn4ActionPerformed
        String Stud_id=delete_student.getText();
            try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            
             Connection cone = ConnectionProvider.getCon();
            Statement ste=cone.createStatement();
            
            st.executeUpdate("delete FROM login_credentials WHERE id_number='"+Stud_id+"'");
               delete_student.setText(" ");
            JOptionPane.showMessageDialog(null, "successfuly deleted ");
            
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_teach_addbtn4ActionPerformed

    private void teach_addbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teach_addbtn5ActionPerformed
      String std_id= stud_id.getText();
 
 try{
     Connection con =ConnectionProvider.getCon();   
       Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("select *from login_credentials where id_number ='"+std_id+"'");
        if (rs.next()){
        stud_name.setText(rs.getString(1));
        stud_ID.setText(rs.getString(2));
        Stud_pass.setText(rs.getString(3));
        }

 }catch(Exception e){
  
    JOptionPane.showMessageDialog(null, e);
}       

        // TODO add your handling code here:
    }//GEN-LAST:event_teach_addbtn5ActionPerformed

    private void teach_addbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teach_addbtn6ActionPerformed
         String student_name= stud_name.getText();
         String student_id=stud_id.getText();
         String student_password=Stud_pass.getText();
    try{
        Connection con =ConnectionProvider.getCon();
        Statement st = con.createStatement();
           st.executeUpdate("update login_credentials set name='"+student_name+"',id_number='"+student_id+"',password='"+student_password+"' where id_number='"+student_id+"'");
        JOptionPane.showMessageDialog(null, "Student Info successfully updated");
          }catch (Exception e){
             JOptionPane.showMessageDialog(null, "connection error");
            
        }
        


        // TODO add your handling code here:
    }//GEN-LAST:event_teach_addbtn6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_page().setVisible(true);
            }
        });
    }
    private void setColor(JButton button){
         button.setBackground(new Color(51,51,51));
    }
    private void resetColor(JButton button2,JButton button3,JButton button1){
        button1.setBackground(new Color(1,1,1));
        button2.setBackground(new Color(1,1,1));     
        button3.setBackground(new Color(1,1,1));       
    }
    private void resetbtnColor(JButton button2,JButton button3,JButton button1,JButton button4){
        button1.setBackground(new Color(204,204,255));
        button2.setBackground(new Color(204,204,255));     
        button3.setBackground(new Color(204,204,255));
        button4.setBackground(new Color(204,204,255));        
    }    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Assign_btn;
    private javax.swing.JButton Std_addbtn;
    private javax.swing.JLabel Stud_name1;
    private javax.swing.JLabel Stud_name10;
    private javax.swing.JLabel Stud_name11;
    private javax.swing.JLabel Stud_name12;
    private javax.swing.JLabel Stud_name2;
    private javax.swing.JLabel Stud_name3;
    private javax.swing.JLabel Stud_name4;
    private javax.swing.JLabel Stud_name9;
    private javax.swing.JTextField Stud_pass;
    private javax.swing.JButton add_coursebtn2;
    private javax.swing.JButton add_sectionbtn;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JTextField course_code1;
    private javax.swing.JComboBox<String> course_list;
    private javax.swing.JComboBox<String> course_list2;
    private javax.swing.JTextField course_name1;
    private javax.swing.JButton delete_coursebtn;
    private javax.swing.JTextField delete_student;
    private javax.swing.JTextField delete_teacher_name;
    private javax.swing.JLabel id;
    private javax.swing.JLabel id1;
    private javax.swing.JLabel id4;
    private javax.swing.JLabel id5;
    private javax.swing.JLabel id6;
    private javax.swing.JLabel id7;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane10;
    private javax.swing.JTabbedPane jTabbedPane11;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane8;
    private javax.swing.JTabbedPane jTabbedPane9;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel name5;
    private javax.swing.JLabel name6;
    private javax.swing.JLabel name7;
    private javax.swing.JTextField sec_number;
    private javax.swing.JComboBox<String> sec_teach;
    private javax.swing.JComboBox<String> sec_teach1;
    private javax.swing.JComboBox<String> sec_teach2;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JTextField std_id;
    private javax.swing.JTextField std_password;
    private javax.swing.JComboBox<String> std_section;
    private javax.swing.JTextField stud_ID;
    private javax.swing.JTextField stud_id;
    private javax.swing.JTextField stud_name;
    private javax.swing.JTextField stud_name1;
    private javax.swing.JButton teach_addbtn;
    private javax.swing.JButton teach_addbtn1;
    private javax.swing.JButton teach_addbtn2;
    private javax.swing.JButton teach_addbtn3;
    private javax.swing.JButton teach_addbtn4;
    private javax.swing.JButton teach_addbtn5;
    private javax.swing.JButton teach_addbtn6;
    private javax.swing.JTextField teach_id;
    private javax.swing.JTextField teach_id1;
    private javax.swing.JTextField teach_id2;
    private javax.swing.JTextField teach_name;
    private javax.swing.JTextField teach_name1;
    private javax.swing.JComboBox<String> teacher_list;
    private javax.swing.JTextField teacher_pass;
    private javax.swing.JTextField teacher_pass1;
    // End of variables declaration//GEN-END:variables
}
