/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pages;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.proteanit.sql.DbUtils;
import project.ConnectionProvider;


/**
 *
 * @author fekede alemayehu
 */
public class stud_page extends javax.swing.JFrame {

    /**
     * Creates new form teacher_page
     */
    public stud_page(String id,String name) {
        initComponents();
        
        username.setText(name);
        id_num.setText(id);
        
     
        
        
     
        try{
            Connection con =ConnectionProvider.getCon();   
              Statement st = con.createStatement();
              String a;
              String b;
              ResultSet rs = st.executeQuery("select count(*) as num, sum(status) as numi from attendance where id_no ='"+id+"'");
               if (rs.next()){
                   a=rs.getString("num");
                   b=rs.getString("numi");
                   double al=Double.parseDouble(a);
                   double som=Double.parseDouble(b);
                   double percentage=(som)/(al)*100;
                   total_progress.setValue((int) percentage);
                   percent.setText(percentage+"%");
                   if (percentage >=80){
                            status.setText("Good");
                   }else
                       status.setForeground(Color.red);
                       status.setText("warning");
            
                   
               }else 
                   JOptionPane.showMessageDialog(null, "error");
                               
        }catch(Exception e){

           JOptionPane.showMessageDialog(null, e);
       }
        
 
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        bg = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        id_num = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        username2 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        att_table = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        monthly_table = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        weekly_table = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        total_progress = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        percent = new javax.swing.JLabel();
        week_progress = new javax.swing.JProgressBar();
        jLabel11 = new javax.swing.JLabel();
        week_percent = new javax.swing.JLabel();
        month_progress = new javax.swing.JProgressBar();
        jLabel12 = new javax.swing.JLabel();
        month_percent = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        course_att_month_list = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        course_att_week_list = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        course_att_alllist = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admni illustration-2.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(150, 130));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        bg.setBackground(new java.awt.Color(51, 0, 51));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(0, 0, 0));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        sidepanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 30, -1, -1));
        sidepanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 250, 10));

        jPanel7.setBackground(new java.awt.Color(255, 51, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stud_illustration 3_2.png"))); // NOI18N
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 240, -1));

        sidepanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 150));

        btn_1.setBackground(new java.awt.Color(0, 0, 0));
        btn_1.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btn_1.setForeground(new java.awt.Color(255, 255, 255));
        btn_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_total_sales_1_26px.png"))); // NOI18N
        btn_1.setText("       Attendance Summary ");
        btn_1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_1.setBorderPainted(false);
        btn_1.setContentAreaFilled(false);
        btn_1.setFocusPainted(false);
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });
        sidepanel.add(btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 250, 50));

        btn_2.setBackground(new java.awt.Color(0, 0, 0));
        btn_2.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btn_2.setForeground(new java.awt.Color(255, 255, 255));
        btn_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_attendance_mark_26px_1.png"))); // NOI18N
        btn_2.setText("       My attendance            ");
        btn_2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_2.setBorderPainted(false);
        btn_2.setContentAreaFilled(false);
        btn_2.setFocusPainted(false);
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });
        sidepanel.add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 250, 50));

        btn_3.setBackground(new java.awt.Color(0, 0, 0));
        btn_3.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btn_3.setForeground(new java.awt.Color(255, 255, 255));
        btn_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_wednesday_30px.png"))); // NOI18N
        btn_3.setText("         This week               ");
        btn_3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_3.setBorderPainted(false);
        btn_3.setContentAreaFilled(false);
        btn_3.setFocusPainted(false);
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });
        sidepanel.add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 250, 50));

        btn_4.setBackground(new java.awt.Color(0, 0, 0));
        btn_4.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btn_4.setForeground(new java.awt.Color(255, 255, 255));
        btn_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_month_view_30px.png"))); // NOI18N
        btn_4.setText("         This Month               ");
        btn_4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_4.setBorderPainted(false);
        btn_4.setContentAreaFilled(false);
        btn_4.setFocusPainted(false);
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });
        sidepanel.add(btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 250, 50));

        id_num.setFont(new java.awt.Font("Bodoni MT", 1, 12)); // NOI18N
        id_num.setForeground(new java.awt.Color(255, 0, 0));
        id_num.setText("ugr/10/12");
        sidepanel.add(id_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 167, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/student.png"))); // NOI18N
        sidepanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel10.setForeground(new java.awt.Color(51, 204, 0));
        jLabel10.setText("@abudah 2021");
        sidepanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 100, -1));

        username.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(0, 204, 0));
        username.setText("yared bayisa");
        sidepanel.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 167, -1));

        username2.setBackground(new java.awt.Color(255, 255, 255));
        username2.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        username2.setForeground(new java.awt.Color(51, 51, 255));
        username2.setText("status: ");
        sidepanel.add(username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 50, -1));

        status.setBackground(new java.awt.Color(255, 255, 255));
        status.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        status.setForeground(new java.awt.Color(0, 255, 51));
        status.setText("good");
        sidepanel.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 50, -1));

        bg.add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 500));

        jTabbedPane7.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jPanel3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel3ComponentShown(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        att_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(att_table);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 720, 370));

        jTabbedPane7.addTab("My Attendance", jPanel3);

        jPanel9.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel9ComponentShown(evt);
            }
        });
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        monthly_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(monthly_table);

        jPanel9.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 740, 340));

        jTabbedPane7.addTab("This Month", jPanel9);

        jPanel10.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel10ComponentShown(evt);
            }
        });
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        weekly_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(weekly_table);

        jPanel10.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 720, 230));

        jTabbedPane7.addTab("This Week", jPanel10);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        total_progress.setForeground(new java.awt.Color(0, 255, 0));
        total_progress.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel4.add(total_progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Total attendance Progress");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        percent.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        percent.setText("P%");
        jPanel4.add(percent, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, 40));

        week_progress.setForeground(new java.awt.Color(0, 255, 0));
        week_progress.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel4.add(week_progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, 40));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("This week attendance Progress");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        week_percent.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        week_percent.setText("P%");
        jPanel4.add(week_percent, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, 40));

        month_progress.setForeground(new java.awt.Color(0, 255, 0));
        month_progress.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel4.add(month_progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, 40));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("This Month attendance Progress");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        month_percent.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        month_percent.setText("P%");
        jPanel4.add(month_percent, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, -1, 40));

        jTabbedPane7.addTab("Attendance Summary", jPanel4);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Select  course name:");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        course_att_month_list.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jPanel6.add(course_att_month_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 190, -1));

        jButton3.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jButton3.setText("Select");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("To Display This Month's Attendance list first Select Course: ");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 410, -1));

        jTabbedPane7.addTab("course type for month", jPanel6);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Select  course name:");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        course_att_week_list.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jPanel8.add(course_att_week_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 190, -1));

        jButton4.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jButton4.setText("Select");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("To Display this week Attendance first Select Course: ");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 410, -1));

        jTabbedPane7.addTab("course type for week", jPanel8);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Select  course name:");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        course_att_alllist.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jPanel5.add(course_att_alllist, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 190, -1));

        jButton2.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jButton2.setText("Select");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("To Display All  Attendance  list first Select Course: ");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 410, -1));

        jTabbedPane7.addTab("course type for all", jPanel5);

        bg.add(jTabbedPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 760, 420));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 760, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 499, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
         // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed

        jTabbedPane7.setSelectedIndex(4);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        // TODO add your handling code here:

        setColor(btn_3);
        resetColor(btn_2,btn_1);
        jTabbedPane7.setSelectedIndex(5);
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        // TODO add your handling code here:

        setColor(btn_2);
        resetColor(btn_1,btn_3);
        jTabbedPane7.setSelectedIndex(6);
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed

        setColor(btn_1);
        resetColor(btn_2,btn_3);
        jTabbedPane7.setSelectedIndex(3);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_1ActionPerformed

    private void jPanel3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel3ComponentShown

        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            String course=(String)course_att_alllist.getSelectedItem();
            String user=id_num.getText();
            ResultSet res = st.executeQuery("select id_number from login_credentials where id_number='"+user+"' ");
            
            if (res.next()){ 
                 String se=res.getString("id_number");
           
                 ResultSet  rs= st.executeQuery("select date,stud_name, id_no,course_name,instructor,status from attendance where course_name='"+course+"' and  id_no='"+user+"'  "  );
                 att_table.setAutoResizeMode(att_table.getColumnCount());
                 att_table.setModel(DbUtils.resultSetToTableModel(rs));
           }else
                JOptionPane.showConfirmDialog(null, "dideeraam namichoo kana dadhabdaa");
            
        }catch (Exception e){
            JOptionPane.showConfirmDialog(null, e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3ComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            jTabbedPane7.setSelectedIndex(0);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            jTabbedPane7.setSelectedIndex(1);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

           jTabbedPane7.setSelectedIndex(2);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jPanel9ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel9ComponentShown


        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            String course=(String)course_att_month_list.getSelectedItem();
            String user=id_num.getText();
            
            ResultSet rest= st.executeQuery("select max(month(date)) as end from attendance;");
            if(rest.next()){
                String latest_month=rest.getString("end");
                 ResultSet  rs= st.executeQuery("select date,stud_name, id_no,course_name,instructor,status from attendance where course_name='"+course+"' and  id_no='"+user+"' and month(date)='"+latest_month+"'  "  ); 
                 monthly_table.setAutoResizeMode(monthly_table.getColumnCount());
                 monthly_table.setModel(DbUtils.resultSetToTableModel(rs));
            }else
                JOptionPane.showConfirmDialog(null, "dideeraam namichoo kana dadhabdaa");
        }catch (Exception e){
            JOptionPane.showConfirmDialog(null, e);
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9ComponentShown

    private void jPanel10ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel10ComponentShown


        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            String course=(String)course_att_week_list.getSelectedItem();
            String user=id_num.getText();
            
            ResultSet rest= st.executeQuery("select max(month(date)) as end from attendance;");
            if(rest.next()){
                String latest_month=rest.getString("end");
                ResultSet restday= st.executeQuery("select max(day(date)) as begun from attendance where month(date)='"+latest_month+"';");
                if(restday.next()){
                    String latest_day=restday.getString("begun");
 
                    ResultSet  rs= st.executeQuery("select date,stud_name, id_no,course_name,instructor,status from attendance where course_name='"+course+"' and  id_no='"+user+"' and month(date)='"+latest_month+"' and day(date)>'"+latest_day+"'-'7' "  ); 
                    weekly_table.setAutoResizeMode(weekly_table.getColumnCount());
                    weekly_table.setModel(DbUtils.resultSetToTableModel(rs));
                }else
                    JOptionPane.showConfirmDialog(null, "Rakkoo Guyyaa");
                    
            }else
                JOptionPane.showConfirmDialog(null, "dideeraam namichoo kana dadhabdaa");
            
        }catch (Exception e){
            JOptionPane.showConfirmDialog(null, e);
        }
        

    
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel10ComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stud_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stud_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stud_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stud_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
//                new stud_page().setVisible(true);
            }
        });
    }
    private void setColor(JButton button){
         button.setBackground(new Color(51,51,51));
    }
    private void resetColor(JButton button2,JButton button3){
        button2.setBackground(new Color(1,1,1));     
        button3.setBackground(new Color(1,1,1));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable att_table;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JComboBox<String> course_att_alllist;
    private javax.swing.JComboBox<String> course_att_month_list;
    private javax.swing.JComboBox<String> course_att_week_list;
    private javax.swing.JLabel id_num;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JLabel month_percent;
    private javax.swing.JProgressBar month_progress;
    private javax.swing.JTable monthly_table;
    private javax.swing.JLabel percent;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JLabel status;
    private javax.swing.JProgressBar total_progress;
    private javax.swing.JLabel username;
    private javax.swing.JLabel username2;
    private javax.swing.JLabel week_percent;
    private javax.swing.JProgressBar week_progress;
    private javax.swing.JTable weekly_table;
    // End of variables declaration//GEN-END:variables
}
