/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pages;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;
import project.ConnectionProvider;

/**
 *
 * @author fekede alemayehu
 */
public class teacher_page extends javax.swing.JFrame {

    /**
     * Creates new form Teacherrrr
     */
    public teacher_page(String id,String name) {
        initComponents();
        acct_name.setText(name);
        teach_id.setText(id);
        try{
        
        Connection con = ConnectionProvider.getCon();
        Statement st=con.createStatement();
        ResultSet res = st.executeQuery("select cname from assigned_courses where instructor='"+name+"' ");
        Assigned_courses.removeAllItems();
        while(res.next()){ 
            String se=res.getString("cname");
            
             Assigned_courses.addItem(se);          
           }
        }catch (Exception e) {
             JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidepanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        acct_name = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        teach_id = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        att_date = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        stud_list = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Assigned_courses = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Stud_listtable = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        selected_date = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Select_table = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        selected_sec = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(0, 0, 0));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        sidepanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 30, -1, -1));
        sidepanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 300, 10));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/teacher_illustratation_2.jpg"))); // NOI18N
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 260, 190));

        sidepanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 150));

        btn_1.setBackground(new java.awt.Color(0, 0, 0));
        btn_1.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btn_1.setForeground(new java.awt.Color(255, 255, 255));
        btn_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_total_sales_1_26px.png"))); // NOI18N
        btn_1.setText("    Attendance Summary          ");
        btn_1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_1.setBorderPainted(false);
        btn_1.setContentAreaFilled(false);
        btn_1.setFocusPainted(false);
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });
        sidepanel.add(btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 250, 50));

        btn_2.setBackground(new java.awt.Color(0, 0, 0));
        btn_2.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btn_2.setForeground(new java.awt.Color(255, 255, 255));
        btn_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_attendance_mark_26px_1.png"))); // NOI18N
        btn_2.setText("    Take attendance                ");
        btn_2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_2.setBorderPainted(false);
        btn_2.setContentAreaFilled(false);
        btn_2.setFocusPainted(false);
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });
        sidepanel.add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 250, 50));

        btn_3.setBackground(new java.awt.Color(0, 0, 0));
        btn_3.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btn_3.setForeground(new java.awt.Color(255, 255, 255));
        btn_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_list_26px.png"))); // NOI18N
        btn_3.setText("    View Attendance By date     ");
        btn_3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_3.setBorderPainted(false);
        btn_3.setContentAreaFilled(false);
        btn_3.setFocusPainted(false);
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });
        sidepanel.add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 260, 50));

        btn_4.setBackground(new java.awt.Color(0, 0, 0));
        btn_4.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btn_4.setForeground(new java.awt.Color(255, 255, 255));
        btn_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_list_26px.png"))); // NOI18N
        btn_4.setText("     My students List                   ");
        btn_4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_4.setBorderPainted(false);
        btn_4.setContentAreaFilled(false);
        btn_4.setFocusPainted(false);
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });
        sidepanel.add(btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 260, 50));

        acct_name.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        acct_name.setForeground(new java.awt.Color(0, 255, 0));
        acct_name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_student_male_26px.png"))); // NOI18N
        acct_name.setText("username");
        sidepanel.add(acct_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 170, 29));

        jLabel10.setForeground(new java.awt.Color(51, 204, 0));
        jLabel10.setText("@abudah 2021");
        sidepanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 100, -1));

        teach_id.setFont(new java.awt.Font("Bodoni MT", 1, 12)); // NOI18N
        teach_id.setForeground(new java.awt.Color(255, 0, 0));
        teach_id.setText("tr/12/10");
        sidepanel.add(teach_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 80, -1));

        jLabel11.setForeground(new java.awt.Color(51, 204, 0));
        jLabel11.setText("@abudah 2021");
        sidepanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 100, -1));

        getContentPane().add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 260, 530));

        jTabbedPane2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        att_date.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(att_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 110, 20));

        jLabel2.setBackground(new java.awt.Color(0, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Course:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 80, 20));

        jLabel3.setBackground(new java.awt.Color(0, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Date:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 20));

        stud_list.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jPanel1.add(stud_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 190, -1));

        jLabel7.setBackground(new java.awt.Color(0, 255, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Student Name : ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 160, 30));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Absent");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("Present");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, -1));

        Assigned_courses.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jPanel1.add(Assigned_courses, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 160, -1));

        jTabbedPane3.addTab("tab1", jPanel1);

        jTabbedPane2.addTab("Take Attendance", jTabbedPane3);

        jPanel4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel4ComponentShown(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton4.setText("Print");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 80, 30));

        Stud_listtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Stud_listtable);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 720, 330));

        jTabbedPane2.addTab("Students List", jPanel4);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(0, 255, 255));
        jLabel8.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel8.setText("Date:");
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 80, 20));

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setText("Select");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("please select the day  you want to view attendance:");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 42, 613, 27));
        jPanel9.add(selected_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 120, 30));

        jTabbedPane2.addTab("Choose date to display the attendace", jPanel9);

        jPanel10.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel10ComponentShown(evt);
            }
        });
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Select_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Select_table);

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 270));

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton6.setText("Print");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 80, 30));

        jTabbedPane2.addTab("Selected date Attendace", jPanel10);
        jTabbedPane2.addTab("summary", jTabbedPane6);

        jPanel3.setBackground(new java.awt.Color(255, 204, 51));
        jPanel3.setForeground(new java.awt.Color(51, 255, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(0, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 0));
        jLabel5.setText("Section: ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 90, 30));

        selected_sec.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        selected_sec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        jPanel3.add(selected_sec, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 140, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Select");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("please select the section you want to take attendance from:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 613, 27));

        jTabbedPane4.addTab("tab1", jPanel3);

        jTabbedPane2.addTab("Select section", jTabbedPane4);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 770, 370));

        jPanel8.setBackground(new java.awt.Color(0, 153, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 790, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed

        setColor(btn_1);
        resetColor(btn_2,btn_4,btn_3);
        jTabbedPane2.setSelectedIndex(4);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        // TODO add your handling code here:

        setColor(btn_2);
        resetColor(btn_1,btn_4,btn_3);
        jTabbedPane2.setSelectedIndex(5);
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
          jTabbedPane2.setSelectedIndex(2);
    }//GEN-LAST:event_btn_3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String instructor=acct_name.getText();
            String section=(String)selected_sec.getSelectedItem();
            String course=(String)Assigned_courses.getSelectedItem();
            String date=att_date.getText();
            String name=(String)stud_list.getSelectedItem();
            Connection con = ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs = st.executeQuery("select *from login_credentials where name ='"+name+"' and section='"+section+"'");
            if (rs.next()){
                String id_number=rs.getString(2);
                st.executeUpdate("INSERT INTO attendance VALUES ('"+date+"','"+id_number+"', '"+name+"', '"+course+"', '0','"+instructor+"','"+section+"');");

            }else
            JOptionPane.showMessageDialog(null,"error");

            // TODO add your handling code here:
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String instructor=acct_name.getText();
            String section=(String)selected_sec.getSelectedItem();
            String course=(String)Assigned_courses.getSelectedItem();
            String date=att_date.getText();
            String name=(String)stud_list.getSelectedItem();
            Connection con = ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs = st.executeQuery("select * from login_credentials where name ='"+name+"' and section='"+section+"'");
            if (rs.next()){
                String id_number=rs.getString(2);
                st.executeUpdate("INSERT INTO attendance VALUES ('"+date+"','"+id_number+"', '"+name+"', '"+course+"', '1','"+instructor+"','"+section+"');");

            }else
            JOptionPane.showMessageDialog(null,"error");

            // TODO add your handling code here:
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            Stud_listtable.print(JTable.PrintMode.FIT_WIDTH);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jPanel4ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel4ComponentShown
        try{Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            String Section=(String)selected_sec.getSelectedItem();
            ResultSet  rs= st.executeQuery("select name, id_number from login_credentials where section='"+Section+"' and role_type= 'student' " );
            Stud_listtable.setAutoResizeMode(Stud_listtable.getColumnCount());
            Stud_listtable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch (Exception e){
            JOptionPane.showConfirmDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4ComponentShown

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        jTabbedPane2.setSelectedIndex(3);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jPanel10ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel10ComponentShown

        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            String date=selected_date.getText();
            ResultSet  rs= st.executeQuery("select stud_name, id_no,course_name,instructor,status from attendance where date='"+date+"'" );
            Select_table.setAutoResizeMode(Select_table.getColumnCount());
            Select_table.setModel(DbUtils.resultSetToTableModel(rs));
        }catch (Exception e){
            JOptionPane.showConfirmDialog(null, e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel10ComponentShown

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
      // TODO add your handling code here:

        setColor(btn_3);
        resetColor(btn_2,btn_4,btn_1);
        jTabbedPane2.setSelectedIndex(1);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed



        try{
        Stud_listtable.print(JTable.PrintMode.FIT_WIDTH);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        
        
        }    // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String section=(String)selected_sec.getSelectedItem();
        stud_list.removeAllItems();

        try{
            Connection con =ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select name from login_credentials where role_type ='student' and section='"+section+"'");
            while(rs.next()){
                String s=rs.getString("name");
                stud_list.addItem(s);
            }
            jTabbedPane2.setSelectedIndex(0);

        }catch(Exception e){

            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacher_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacher_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacher_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacher_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             //   new teacher_page().setVisible(true);
            }
        });
    }
    private void setColor(JButton button){
         button.setBackground(new Color(51,51,51));
    }
    private void resetColor(JButton button2,JButton button3,JButton button4){
        button2.setBackground(new Color(1,1,1));     
        button3.setBackground(new Color(1,1,1));
        button4.setBackground(new Color(1,1,1));
    }
    private void resetbtnColor(JButton button2,JButton button3,JButton button1,JButton button4){
        button1.setBackground(new Color(204,204,255));
        button2.setBackground(new Color(204,204,255));     
        button3.setBackground(new Color(204,204,255));
        button4.setBackground(new Color(204,204,255));        
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Assigned_courses;
    private javax.swing.JTable Select_table;
    private javax.swing.JTable Stud_listtable;
    private javax.swing.JLabel acct_name;
    private javax.swing.JTextField att_date;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTextField selected_date;
    private javax.swing.JComboBox<String> selected_sec;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JComboBox<String> stud_list;
    private javax.swing.JLabel teach_id;
    // End of variables declaration//GEN-END:variables
}
